name: Contributing to Language Model Planyground

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
  
    - name: Check annotations
      run: |
        # pipenv run mypy lmp test --ignore-missing-imports

    - name: Lint code with flake8
      run: |
        pipenv run ly li lf

    - name: Run tests
      run: |
        # pipenv run tset
        # pipenv run test-coverage